#!/usr/bin/env zsh

# fname="$1"

<&0 \
	| sed -e '/^</,$d' \
	| sed -e '/Accepted Talks/,$d' \
	| perl -lpe 's/.* (.*?day, \d\d July, 2018).*/\n\1/' \
	| perl -lpe 's/.*(\d\d:\d\d).*?(\d\d:\d\d).*\[(.*?)\]\{style="text-decoration.*?\*(.*?)\*.*?([(invited talk)])*.*Abstract.*/\1 - \2 ; \3 ; \4/' \
	| perl -lpe 's/.*([SPLl]+\d\.\d).*(\d\d:\d\d).*?(\d\d:\d\d).*?Chair.*?: (.*?)]\{style.*/\n\2 - \3 ; \1 Chair: \4/'
